// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/google/uuid"
)

type Message struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	Content    string
	ExternalID uuid.UUID
}
