// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/google/uuid"
)

type Counter struct {
	ID    uuid.UUID
	Value []int64
}

type Message struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	Content    string
	ExternalID []uuid.UUID
}
